apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: 2019-08-19T19:38:54Z
  generateName: kubia-
  labels:
    run: kubia
  name: kubia-djphw
  namespace: default
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicationController
    name: kubia
    uid: 8f658c61-c2b2-11e9-9728-080027f62c54
  resourceVersion: "189636"
  selfLink: /api/v1/namespaces/default/pods/kubia-djphw
  uid: fac630b6-c2b8-11e9-9728-080027f62c54
spec:
  containers:
  - image: phantom0610/zuzeze
    imagePullPolicy: Always
    name: kubia
    ports:
    - containerPort: 8080
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-vf9lr
      readOnly: true
  dnsPolicy: ClusterFirst
  nodeName: minikube
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-vf9lr
    secret:
      defaultMode: 420
      secretName: default-token-vf9lr
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2019-08-19T19:38:54Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2019-08-21T19:51:55Z
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: 2019-08-21T19:51:55Z
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: 2019-08-19T19:38:54Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://b8b50fc4e54d4bb3276db71cb2526dca7f39ab2ed1673415d5d49c06a988d205
    image: phantom0610/zuzeze:latest
    imageID: docker-pullable://phantom0610/zuzeze@sha256:bf805d315577246b403cd4362aafe483ab88911f26429620e8568f65975fb3cc
    lastState:
      terminated:
        containerID: docker://d14e560474126c471134d3358b8c4f49d3894b1b9debe62edc7ac0bceb41f00e
        exitCode: 137
        finishedAt: 2019-08-20T19:11:30Z
        reason: Error
        startedAt: 2019-08-19T19:38:59Z
    name: kubia
    ready: true
    restartCount: 1
    state:
      running:
        startedAt: 2019-08-21T19:51:54Z
  hostIP: 10.0.2.15
  phase: Running
  podIP: 172.17.0.6
  qosClass: BestEffort
  startTime: 2019-08-19T19:38:54Z
