apiVersion: v1
kind: Namespace
metadata:
  name: anhties

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: escluster
  namespace: anhties
reclaimPolicy: Retain
provisioner: k8s.io/minikube-hostpath
volumeBindingMode: Immediate

---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: es-master
  namespace: anhties
  labels:
    component: elasticsearch
    role: master
spec:
  serviceName: es-master
  replicas: 3
  selector:
    matchLabels:
      component: elasticsearch
      role: master    
  template:
    metadata:
      namespace: anhties
      labels:
        component: elasticsearch
        role: master
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
      containers:
      - name: elasticsearch
        resources:
            requests:
                memory: 512Mi
        securityContext:
          privileged: true
          runAsUser: 1000
          capabilities:
            add:
            - IPC_LOCK
            - SYS_RESOURCE
        image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
        env:
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: cluster.name
          value: my-es
        - name: node.data
          value: "false"
        - name: node.ingest
          value: "false"
        - name: node.master
          value: "true"
        - name: ES_JAVA_OPTS
          value: -Xms256m -Xmx256m
        - name: bootstrap.memory_lock
          value: "false"
        - name: discovery.zen.ping.unicast.hosts
          value: elasticsearch-discovery
        - name: discovery.zen.minimum_master_nodes
          value: "1"
        ports:
        - containerPort: 9200
          name: es-http
        - containerPort: 9300
          name: es-transport
        volumeMounts:
        - name: storage
          mountPath: /usr/share/elasticsearch/data
  volumeClaimTemplates:
  - metadata:
      name: storage
      namespace: anhties
      labels:
        component: elasticsearch
        role: master
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: escluster
      resources:
        requests:
          storage: 512Mi

---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-discovery
  namespace: anhties
  labels:
    component: elasticsearch
    role: master
spec:
  selector:
    component: elasticsearch
    role: master
  ports:
  - name: transport
    port: 9300
    protocol: TCP
  clusterIP: None

---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-http
  namespace: anhties
  labels:
    component: elasticsearch
    role: master
spec:
  selector:
    component: elasticsearch
    role: master
  ports:
  - name: http
    port: 9200
    targetPort: 9200
  type: NodePort